# This notebook contains the following Python tutorials
1. Object-orientied programming
2. Matrix calculus using numpy
3. Statistical analysis using pandas
4. Write/read results to SQLDB 

Further explanation of notebook can be found in following blog:

## 1: Object-orientied programming

### 1a. Load necessary libraries

In [27]:
# Load necessary libraries
import numpy as np
from datetime import date

### 1b. Create 3 classes

In [39]:
# Class 1: Player
class Player(object):
    _posList = {'goalkeeper', 'defender', 'midfielder', 'striker'}
    
    def __init__(self,name):
        self._playerName=name
        self._trainingList=[]
        self._rawData = np.empty((0,3), int)
        
    def setPosition(self, pos):
        if pos in self._posList:
            self._position=pos
            print(self._playerName + " is " + pos)
        else:
            raise ValueError("Value {} not in list.".format(pos))        

    def setTraining(self, t, rawData):
        self._trainingList.append(t)
        self._rawData = np.append(self._rawData, rawData, axis=0)
        
    def getTrainingRawData(self):
        return self._rawData

    def getTrainingFilter(self, stage, tt, date):
        for index, training in enumerate(self._trainingList):
            if training.getStage() == stage and training.getTrainingType() == tt and training.getDate() == date:
                return self._rawData[index]

    def setAge(self, age):
        self._age = age
            
    def getName(self):
        return self._playerName

In [40]:
# Class 2: FirstTeamPlayer
class FirstTeamPlayer(Player):
    def __init__(self,ftp):
        Player.__init__(self, ftp)

    def setPosition(self,pos1, pos2):
        if pos1 in self._posList and pos2 in self._posList:
            self._posComp=pos1
            self._posCL=pos2
            print(self._playerName + " is " + pos1)
            print(self._playerName + " is " + pos2 + " in the CL")
        else:
            raise ValueError("Pos {},{} unknown".format(pos1, pos2))   

    def setNumber(self,number):
        self._number=number
        print(self._playerName + " has number " + str(number))

In [41]:
# Class 3: Training
class Training(object):
    _stageList = {'ArenA', 'Toekomst', 'Pool', 'Gym'}
    _trainingTypeList = {'strength', 'technique', 'friendly game'}

    def __init__(self, stage, tt, date):
        if stage in self._stageList:
            self._stage = stage
        else:
            raise ValueError("Value {} not in list.".format(stage))
        if tt in self._trainingTypeList:
            self._trainingType = tt
        else:
            raise ValueError("Value {} not in list.".format(tt))

        #todo: Valid date test (no static type checking in Python)
        self._date = date

    def getStage(self):
        return self._stage

    def getTrainingType(self):
        return self._trainingType

    def getDate(self):
        return self._date

### 1c. Inheritance

In [42]:
# Construct two players, FirstTeamPlayer class inherits from Player class
player1 = Player("Janssen")
player2 = FirstTeamPlayer("Tadic")

In [43]:
# Set age of players. Notice that setAge method is inherited and is not present in class FirstTeamPlayer
player1.setAge(20)
player2.setAge(30)

### 1d. Polymorphism

In [44]:
# Set position of player. Notice that setPosition method is redefined (overloaded) in class FirstTeamPlayer
player1.setPosition("goalkeeper")
player2.setPosition("midfielder", "striker")

Janssen is goalkeeper
Tadic is midfielder
Tadic is striker in the CL


In [45]:
# Set Numer of Player. Notice that setNumber method is only present in class  
player2.setNumber(10)
#player.setNumber(99) will result in failure

Tadic has number 10


### 1e. Data encapsulation

In [46]:
# Create new traning object and add traningsdata to player object. Notice that a numpy array is used as attribute
training1=Training('Toekomst', 'strength', date(2019,4,19))
player1.setTraining(training1, rawData=np.random.rand(1,3))
player2.setTraining(training1, rawData=np.random.rand(1,3))

In [47]:
# Add two new trainings objects
training2=Training('ArenA', 'friendly game', date(2019,4,20))
player1.setTraining(training2, rawData=np.random.rand(1,3))
player2.setTraining(training2, rawData=np.random.rand(1,3))

training3=Training('Gym', 'strength', date(2019,4,20))
player1.setTraining(training3, rawData=np.random.rand(1,3))
player2.setTraining(training3, rawData=np.random.rand(1,3))

In [48]:
# Retrieve data using get methods. Notice that if an attribute does not have get method, its data cannot be retrieved
print ("All trainingdata from player: " + player1.getName())
print (player1.getTrainingRawData())
print ("All trainingdata from player: " + player2.getName())
print (player2.getTrainingRawData())
print ("Trainingdata from player " + player1.getName() + " for first training ")
print (player1.getTrainingFilter('ArenA', 'friendly game', date(2019,4,20)))
print ("Trainingdata from player " + player2.getName() + " for last training ")
print (player2.getTrainingFilter('Gym', 'strength', date(2019,4,20)))

All trainingdata from player: Janssen
[[0.16602664 0.00540508 0.95183772]
 [0.47523239 0.65681941 0.23890372]
 [0.53569236 0.97794    0.5954682 ]]
All trainingdata from player: Tadic
[[0.49086482 0.46700214 0.9096877 ]
 [0.69306806 0.36328726 0.8852503 ]
 [0.3731209  0.09477548 0.60024675]]
Trainingdata from player Janssen for first training 
[0.47523239 0.65681941 0.23890372]
Trainingdata from player Tadic for last training 
[0.3731209  0.09477548 0.60024675]


In [49]:
# this will not work
#player.getAge()
# This still works and differs from Java, C#. See explanation: https://stackoverflow.com/questions/797771/python-protected-attributes
player1._age

20

## 2: Matrix calculus using numpy

## 2a. Create numpy matrix data

In [50]:
# Take the matrix data from player objecs that were created earlier
m1=player1.getTrainingRawData()
m2=player2.getTrainingRawData()
print(m1)
print(m2)

[[0.16602664 0.00540508 0.95183772]
 [0.47523239 0.65681941 0.23890372]
 [0.53569236 0.97794    0.5954682 ]]
[[0.49086482 0.46700214 0.9096877 ]
 [0.69306806 0.36328726 0.8852503 ]
 [0.3731209  0.09477548 0.60024675]]


## 2b. Simple operations

In [51]:
#Access values
print(m1.shape)

print(m1[0][1])
print(m1[0,1])
print(m1[0])

print(m1[0:1])
print(m1[0:2])

print(m1[:,0])
print(m1[0:1,0:])
print(m1[1:3,1:3])

(3, 3)
0.005405075953237359
0.005405075953237359
[0.16602664 0.00540508 0.95183772]
[[0.16602664 0.00540508 0.95183772]]
[[0.16602664 0.00540508 0.95183772]
 [0.47523239 0.65681941 0.23890372]]
[0.16602664 0.47523239 0.53569236]
[[0.16602664 0.00540508 0.95183772]]
[[0.65681941 0.23890372]
 [0.97794    0.5954682 ]]


In [52]:
#Arithmetic
tmp1=m1-m2
tmp2=m1+m2
tmp3=m1*m2 # [m2_11*m1_11,  ..,  m1_33*m2_33]
tmp4=m1/m2 # [m2_11/m1_11,  ..,  m1_33/m2_33]

print(tmp1)
print(tmp2)
print(tmp3)
print(tmp4)

[[-0.32483818 -0.46159707  0.04215002]
 [-0.21783567  0.29353215 -0.64634658]
 [ 0.16257146  0.88316451 -0.00477855]]
[[0.65689146 0.47240722 1.86152542]
 [1.16830045 1.02010668 1.12415402]
 [0.90881326 1.07271548 1.19571495]]
[[0.08149664 0.00252418 0.86587506]
 [0.32936839 0.23861413 0.21148959]
 [0.19987802 0.09268474 0.35742785]]
[[ 0.33823292  0.01157399  1.0463346 ]
 [ 0.68569368  1.80798911  0.26987138]
 [ 1.4357072  10.31849118  0.99203902]]


### 2c. Matrix operations

In [53]:
tmp1 = m1.dot(m2) # [m1_11 * m2_11 + m1_23 * m2_32 +  m1_13 * m2_31, ..., m1_31 * m2_13 + m1_23 * m2_32 +  m1_33 * m2_33]
tmp2 = m1.dot(np.array([0,1,2])) 
tmp3 = m1 + 1

print(tmp1)
print(tmp2)
print(tmp3)

[[0.44039327 0.16970927 0.72715474]
 [0.77763539 0.48319089 1.15716382]
 [1.16291314 0.66187841 1.71046228]]
[1.90908051 1.13462685 2.1688764 ]
[[1.16602664 1.00540508 1.95183772]
 [1.47523239 1.65681941 1.23890372]
 [1.53569236 1.97794    1.5954682 ]]


In [54]:
#more advanced operations
# tranpose matrix
tmp1 = m1.T
print(tmp3)

# inverse matrix
m1_inv = np.linalg.inv(m1)
print("inverse matrix")
print(m1_inv)
print(m1.dot(m1_inv))

# calculate eigenvalues
tmp2, tmp3 = np.linalg.eig(m1)
print("eigen values")
print(tmp2)
print(tmp3)

# singular value decomposition
u, s, vh = np.linalg.svd(m1, full_matrices=True)
print("singular value decomposition")
print(u)
print(s)
print(vh)

[[1.16602664 1.00540508 1.95183772]
 [1.47523239 1.65681941 1.23890372]
 [1.53569236 1.97794    1.5954682 ]]
inverse matrix
[[ 1.18615339  6.98685882 -4.69917969]
 [-1.16751395 -3.09587315  3.10830941]
 [ 0.85033133 -1.20111995  0.80201526]]
[[ 1.00000000e+00  8.01727023e-17 -1.35065106e-16]
 [-2.92855762e-16  1.00000000e+00 -2.93091080e-16]
 [-1.32973128e-16 -7.00122415e-17  1.00000000e+00]]
eigen values
[ 1.56632296+0.j         -0.07400435+0.28157877j -0.07400435-0.28157877j]
[[ 0.50170359+0.j          0.83317346+0.j          0.83317346-0.j        ]
 [ 0.45534561+0.j         -0.38540009-0.22948836j -0.38540009+0.22948836j]
 [ 0.73549567+0.j         -0.20791815+0.24777791j -0.20791815-0.24777791j]]
singular value decomposition
[[-0.39864495  0.90454617 -0.15125615]
 [-0.49215348 -0.35016653 -0.7969745 ]
 [-0.77386507 -0.24326862  0.58476767]]
[1.61223585 0.79741315 0.10327066]
[[-0.44325188 -0.6712444  -0.5941033 ]
 [-0.18378033 -0.58063897  0.79314764]
 [-0.87735544  0.46074869  0.13

## 3. Statistical analysis using pandas

### 3a. Load libraries, create Pandas dataframes

In [55]:
# load libraries
import pandas as pd

In [56]:
# Create the same matrices as earlier
m1=player1.getTrainingRawData()
m2=player2.getTrainingRawData()

columns = np.array(['col1', 'col2', 'col3'])

# Create pandas dataframe
df_1=pd.DataFrame(data=m1, columns=columns)
df_2=pd.DataFrame(data=m2, columns=columns)

In [57]:
data = player1.getTrainingRawData()
columns = np.array(['col1', 'col2', 'col3'])
print(data)
print(data[0])

df_1=pd.DataFrame(data=data, columns=columns)

print(df_1)
print(df_2)

[[0.16602664 0.00540508 0.95183772]
 [0.47523239 0.65681941 0.23890372]
 [0.53569236 0.97794    0.5954682 ]]
[0.16602664 0.00540508 0.95183772]
       col1      col2      col3
0  0.166027  0.005405  0.951838
1  0.475232  0.656819  0.238904
2  0.535692  0.977940  0.595468
       col1      col2      col3
0  0.490865  0.467002  0.909688
1  0.693068  0.363287  0.885250
2  0.373121  0.094775  0.600247


### 3b. Simple operations

In [58]:
print(df_1['col1'])
print(df_1.iloc[0])
print(df_1[['col1', 'col2']])
print(df_1[['col1', 'col2']].iloc[1:2])

tmp1 = df_1 - df_2
tmp2 = df_1 + df_2
tmp3 = df_1 * df_2
tmp4 = df_1 / df_2

print(tmp1)
print(tmp2)
print(tmp3)
print(tmp4)

0    0.166027
1    0.475232
2    0.535692
Name: col1, dtype: float64
col1    0.166027
col2    0.005405
col3    0.951838
Name: 0, dtype: float64
       col1      col2
0  0.166027  0.005405
1  0.475232  0.656819
2  0.535692  0.977940
       col1      col2
1  0.475232  0.656819
       col1      col2      col3
0 -0.324838 -0.461597  0.042150
1 -0.217836  0.293532 -0.646347
2  0.162571  0.883165 -0.004779
       col1      col2      col3
0  0.656891  0.472407  1.861525
1  1.168300  1.020107  1.124154
2  0.908813  1.072715  1.195715
       col1      col2      col3
0  0.081497  0.002524  0.865875
1  0.329368  0.238614  0.211490
2  0.199878  0.092685  0.357428
       col1       col2      col3
0  0.338233   0.011574  1.046335
1  0.685694   1.807989  0.269871
2  1.435707  10.318491  0.992039


In [59]:
## 3c. Simple operations

row_count=df_1.col1.count()
col_count=len(df_1.columns)
# add column
tmp1 = df_1.assign(col4=pd.Series(np.random.rand(row_count)).values)
# add record
tmp2 = df_1.loc[df_1.index.max()+1] = np.random.rand(col_count)
# remove column
tmp3 = df_1.drop(['col1'], axis=1)
# remove record
tmp4 = df_1.drop(1)

print(tmp1)
print(tmp2)
print(tmp3)
print(tmp4)

       col1      col2      col3      col4
0  0.166027  0.005405  0.951838  0.630991
1  0.475232  0.656819  0.238904  0.815288
2  0.535692  0.977940  0.595468  0.676231
[0.14332821 0.01458826 0.99283739]
       col2      col3
0  0.005405  0.951838
1  0.656819  0.238904
2  0.977940  0.595468
3  0.014588  0.992837
       col1      col2      col3
0  0.166027  0.005405  0.951838
2  0.535692  0.977940  0.595468
3  0.143328  0.014588  0.992837


### 3c. Statistical operations

In [60]:
tmp1=df_1.stack().sum() 
tmp2=df_1.stack().mean() 
tmp3=df_1.stack().median() 
tmp4=df_1.stack().std() 

print("statistics all")
print("sum all:" + str(tmp1))
print("mean all:" + str(tmp2))
print("median all:" + str(tmp3))
print("std all:" + str(tmp4))

tmp1=df_1['col1'].sum()
tmp2=df_1['col1'].mean()
tmp3=df_1['col1'].median()
tmp4=df_1['col1'].std()

print("statistics col1")
print("sum col1:" + str(tmp1))
print("mean col1:" + str(tmp2))
print("median col1:" + str(tmp3))
print("std col1:" + str(tmp4))

statistics all
sum all:5.754079368321005
mean all:0.4795066140267504
median all:0.5054623765822894
std all:0.36843646677038383
statistics col1
sum col1:1.320279603942682
mean col1:0.3300699009856705
median col1:0.320629515541479
std col1:0.20423466536737886


In [61]:
print("multiple statistics")
tmp1=df_1.stack().describe()
tmp2=df_1['col1'].describe()

print("statistics all:" + str(tmp1))
print("statistics col1:" + str(tmp2))

multiple statistics
statistics all:count    12.000000
mean      0.479507
std       0.368436
min       0.005405
25%       0.160352
50%       0.505462
75%       0.730574
max       0.992837
dtype: float64
statistics col1:count    4.000000
mean     0.330070
std      0.204235
min      0.143328
25%      0.160352
50%      0.320630
75%      0.490347
max      0.535692
Name: col1, dtype: float64


In [62]:
tmp1=df_1.cov()
tmp2=df_1.corr()

print("correlation:\n " + str(tmp1))
print("\n")
print("covariance:\n " + str(tmp2))

correlation:
           col1      col2      col3
col1  0.041712  0.097607 -0.061475
col2  0.097607  0.234490 -0.130261
col3 -0.061475 -0.130261  0.124201


covariance:
           col1      col2      col3
col1  1.000000  0.986938 -0.854097
col2  0.986938  1.000000 -0.763288
col3 -0.854097 -0.763288  1.000000


## 4. Write/read results to SQLDB 

### 4a. Load necessary libraries

In [63]:
import pyodbc

### 4b. Create tables in SQLDB

In [64]:
# Go to your SQLDB using SQL Server Management Studio (SMSS) and execute to following script in SQLDB:
script = """

USE [Master]
GO

CREATE DATABASE pythontest
GO

USE [pythontest]

CREATE TABLE [dbo].[trainingsdata]
(  
 [col1] [float] NOT NULL,
 [col2] [float] NOT NULL,
 [col3] [float] NOT NULL
)
GO

"""

### 4c. Create connection

In [65]:
server  = 'demo-dsvmwin-vm'
database = 'pythontest'
driver= '{ODBC Driver 17 for SQL Server}'

In [66]:
# Make connection to database
cnxn = pyodbc.connect('DRIVER='+driver+';SERVER='+server+';PORT=1433;DATABASE='+database + ';Trusted_Connection=yes;')
cursor = cnxn.cursor()

### 4d. Write/read results to SQLDB

In [67]:
#Write results, use pandas dataframe
for index,row in df_1.iterrows():
    cursor.execute("INSERT INTO dbo.trainingsdata([col1],[col2],[col3]) VALUES (?,?,?)", row['col1'], row['col2'], row['col3'])
    cnxn.commit()

In [68]:
#Read results, use pandas dataframe
sql = "SELECT [col1], [col2], [col3] FROM dbo.trainingsdata"
df_1read = pd.read_sql(sql,cnxn)
print(df_1read)
cursor.close()

        col1      col2      col3
0   0.582270  0.031003  0.802630
1   0.104255  0.641051  0.133616
2   0.172017  0.497840  0.225676
3   0.348590  0.854295  0.151956
4   0.147089  0.216612  0.792685
5   0.393516  0.940553  0.696722
6   0.918742  0.952831  0.274990
7   0.151195  0.640710  0.058623
8   0.621080  0.493776  0.573558
9   0.221855  0.412839  0.266007
10  0.918742  0.952831  0.274990
11  0.151195  0.640710  0.058623
12  0.621080  0.493776  0.573558
13  0.221855  0.412839  0.266007
14  0.918742  0.952831  0.274990
15  0.151195  0.640710  0.058623
16  0.621080  0.493776  0.573558
17  0.221855  0.412839  0.266007
18  0.166027  0.005405  0.951838
19  0.475232  0.656819  0.238904
20  0.535692  0.977940  0.595468
21  0.143328  0.014588  0.992837
